### PR TITLE
add 2.2.10 and update :latest to it

### PR DESCRIPTION
**Pull request by tisdall**
2.2.10 was released Sep 07, 2015

I tried to follow the conventions you used when adding the other releases.  

I can't seem to find where the description text on https://hub.docker.com/r/leodido/sphinxsearch/ is pulled from, but it seems to still say 2.2.4 so it's not being updated.  Same issue exists at https://hub.docker.com/r/leodido/sphinxsearch/~/dockerfile/

### CODE REVIEW

**Comment by tisdall** [comment]
Okay, I forgot to create a separate branch for the last two commits but hopefully it's all acceptable...  If you'd like me to break it up into separate ones I can.

Essentially I created a bash script (well modified an existing one) to update all the different sphinxsearch versions based on a template.  Currently there were some differences in the versions.

The last commit is all the changes created from running the update script.

Also, I think it'd be a good idea to get rid of the "latest" directory and simply tag the latest one via Docker's hub configuration.  I updated it any way in case there was a reason to keep it.

I also fixed an issue with a missing `$` in the Dockerfile meaning an ENV value wasn't being used properly.

**Comment by tisdall** [comment]
Oh, the template pattern thing is borrowed from https://github.com/docker-library/postgres/

**Comment by tisdall** [comment]
It seems curl fetched a slightly corrupted `en.pak` file...  I re-fetched it and am testing it out before submitting another commit.

**Comment by tisdall** [comment]
found another issue...  the container wasn't properly shutting down which left my RT indexes not properly closed.  The last commit fixes that.

**Comment by tisdall** [comment]
hello?  ^_^

**Comment by leodido** [comment]
Hi @tisdall, sorry for the very late reply.

I have given a quick look at your work: impressive :+1: 

Tomorrow or very soon (I promise) I'll look to merge.

However I am working on a new version of sphinxsearch docker image that I hope to release soon.

**Pull request merged**
